# Generated by Django 4.1.4 on 2023-03-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicecloneapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='gender',
        ),
    ]
